# Generated by Django 3.2 on 2024-05-20 20:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='user_role',
            new_name='role',
        ),
    ]
