# Generated by Django 3.2 on 2024-06-03 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_rename_user_role_customuser_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='confirmation_code',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Код подтверждения'),
        ),
    ]
