# reviews/models
NAME_MAX_LENGTH = 256
TEXT_MAX_LENGTH = 256
SLUG_MAX_LENGTH = 50
TEXT_ADMIN_ZONE_MAX_LENGTH = 30
TEXT_ADMIN_ZONE_MAX_LENGTH = 30

# users/models
ROLE_MAX_LENNGTH = 20
EMAIL_MAX_LENNGTH = 254
CODE_MAX_LENNGTH = 250

# api/serializers
USERNAME_MAX_LENNGTH = 150
MAX_SCORE = 10
MIN_SCORE = 1
