# reviews/models
TEXT_MAX_LENGTH = 256
SLUG_MAX_LENGTH = 50
NAME_MAX_LENGTH = 256

# users/models
ROLE_MAX_LEGTH = 20
EMAIL_MAX_LEGTH = 254
CODE_MAX_LEGTH = 250
TEXT_ADMIN_ZONE_MAX_LENGTH = 30

# api/serializers
USERNAME_MAX_LENGTH = 150
MAX_SCORE = 10
MIN_SCORE = 1
