# Generated by Django 3.2 on 2024-05-24 21:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0006_review_unique_author_title'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Genres',
            new_name='Genre',
        ),
        migrations.RenameModel(
            old_name='Titles',
            new_name='Title',
        ),
    ]
